### ISSUE TITLE
install.sh fails to wget ORx resources

### ISSUE THREAD

**Issue by davidhoness** [Outernet-Project/orx-install#43]
You get a 404 for both the data delivery agent and librarian install because:

This is in **debs** sub folder: http://outernet-project.github.io/orx-install/debs/ondd_0.1.0-0_armhf.deb
This is in **src** sub folder: http://outernet-project.github.io/orx-install/src/librarian-0.1b3.tar.gz

I was able to make it work by editing my local copy.

**Comment by ben-en** [comment]
Thanks for the report and included fix. :)
