### ISSUE TITLE
How does this work exactly?

### ISSUE THREAD

**Issue by laptopdude90** [Outernet-Project/orx-install#45]
SDRs can only receive, not transmit. So how does it "request" information to be sent to it, like with the TCP/IP protocol?

Also, which frequency does it use?

**Comment by foxbunny** [comment]
ORx does not support SDR for now. Currently, only Ku and C bands are supported via DVB-S/S2 tuners.

As for sending data upstream, we currently do not have an implementation.

Hope this answers your questions. Closing this issue, but feel free to continue the discussion in our [forums](http://discuss.outernet.is/).
